-- MySQL Script generated by MySQL Workbench
-- Mon Mar 26 15:00:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema legohouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema legohouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `legohouse` DEFAULT CHARACTER SET latin1 ;
USE `legohouse` ;

-- -----------------------------------------------------
-- Table `legohouse`.`legoblocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legohouse`.`legoblocks` (
  `legoblockName` VARCHAR(45) NOT NULL,
  `length` INT(11) NOT NULL,
  `thickness` INT(11) NOT NULL,
  PRIMARY KEY (`legoblockName`),
  UNIQUE INDEX `legoblockName_UNIQUE` (`legoblockName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `legohouse`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legohouse`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(90) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(20) NOT NULL DEFAULT 'customer',
  `usercreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `legohouse`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legohouse`.`orders` (
  `OrderId` INT(11) NOT NULL AUTO_INCREMENT,
  `User_userId` INT(11) NOT NULL,
  `ordertime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `length` INT(11) UNSIGNED NOT NULL,
  `width` INT(11) UNSIGNED NOT NULL,
  `hight` INT(11) UNSIGNED NOT NULL,
  `sendt` BIT(1) NOT NULL DEFAULT b'0',
  `confermtime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`OrderId`),
  INDEX `user` (`userId` ASC),
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `legohouse`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `legohouse`.`orderdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legohouse`.`orderdetails` (
  `id` INT(11) NOT NULL,
  `quantity` INT(10) UNSIGNED NOT NULL,
  `legoblockName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `legoblockName`),
  INDEX `legoblockName` (`legoblockName` ASC),
  CONSTRAINT `odetails_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `legohouse`.`orders` (`OrderId`),
  CONSTRAINT `odetails_ibfk_2`
    FOREIGN KEY (`legoblockName`)
    REFERENCES `legohouse`.`legoblocks` (`legoblockName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
